### ISSUE TITLE
Release for ROS 2 Galactic

### ISSUE THREAD

**Issue by SMRazaRizvi96** [pal-robotics/backward_ros#12]
Are there any plans for a release compatible with ROS 2 Galactic?

**Comment by vatanaksoytezer** [comment]
@SMRazaRizvi96 It is already released here: https://github.com/ros/rosdistro/pull/30209

**Comment by SMRazaRizvi96** [comment]
The release repository is unknown. See [here](https://github.com/pal-gbp/backward_ros-release#:~:text=backward_ros%20(galactic)%20%2D%201.0.1%2D2)

![image](https://user-images.githubusercontent.com/74411560/161262670-21c5fb14-5c87-4b47-abe9-4dd62b04e9cc.png)
