### ISSUE TITLE
Trying to compile it on Windows

### ISSUE THREAD

**Issue by SENAI-GilmarCorreia** [pal-robotics/backward_ros#19]
Hello ROS Developers,

I was trying to build this package for use on Windows and encountered the following issue:

```bash
C:/my_folder_ws/install/backward_ros/lib/libbackward.so
  referenced by variable backward_ros_LIBRARIES does not exist!
```

In the Windows environment, the package compiles, but it was built as /lib/backward.lib.

Manually changing the value of backward_ros_LIBRARIES inside backward_rosConfig.cmake.in worked for me, but I think it would be valuable to have this configuration handled automatically as well.

Thank you!

**Comment by saikishor** [comment]
Hello @SENAI-GilmarCorreia!

The pull request is merged and released to all ROS 2 Distros!
https://github.com/ros/rosdistro/pull/43375
https://github.com/ros/rosdistro/pull/43376
https://github.com/ros/rosdistro/pull/43377
https://github.com/ros/rosdistro/pull/43378
