### ISSUE TITLE
Release ?

### ISSUE THREAD

**Issue by olivier-stasse** [pal-robotics/backward_ros#2]
Sorry to be a bother, but then would it be possible to have a release of the package ?

**Comment by v-lopez** [comment]
You mean for ros-kinetic, indigo or one of our internal pal- packages?

**Comment by olivier-stasse** [comment]
For ros-kinetic would be fine for me.

**Comment by v-lopez** [comment]
Sure, I'm working on it.

FYI: https://github.com/ros/rosdistro/pull/17654

**Comment by olivier-stasse** [comment]
Wonderful ! Many thanks ! :+1:

**Comment by 130s** [comment]
Great work, thanks!

https://github.com/ros/rosdistro/pull/17654 was just a dependency of this package so the ticket can remain open, if I'm not mistaken.

**Comment by v-lopez** [comment]
Release requested here: https://github.com/ros/rosdistro/pull/17672

**Comment by Timple** [comment]
Is released for kinetic now as far as I can tell.

**Comment by v-lopez** [comment]
Indeed.
