### ISSUE TITLE
Tests compilation failure

### ISSUE THREAD

**Issue by veimox** [pal-robotics/backward_ros#4]
There is a compilation error in the tests due to not finding the headers. To reproduce, set the test flag to TRUE. I find two errors: one in the `backwards.hpp`main header and the other in the `test.hpp` header. The error is something like:
```bash
/blablabla/src/backward_ros/test/test.cpp:27:10: fatal error: test/test.hpp: No such file or directory
 #include "test/test.hpp"
          ^~~~~~~~~~~~~~~
/moreblablabla/src/backward_ros/test/stacktrace.cpp:24:10: fatal error: backward.hpp: No such file or directory
 #include "backward.hpp"
          ^~~~~~~~~~~~~~
```
I can think of two solutions:

1. Changing the include headers. E.g. the backward could be `#include <backward_ros/backward.hpp>"`. For the "test/test.hpp" I think is better to do `#include "test.hpp"`
2. Adding the folders to the include directories. This would be to add:
```cmake
	include_directories(
		.
		include/backward_ros
	)
```
I prefer the first one because is more scalable and explicit. I have done a PR in  #3 with this solution.

**Comment by v-lopez** [comment]
Thanks for the issue and the PR.
