### ISSUE TITLE
Foxy / Galactic / Rolling release

### ISSUE THREAD

**Issue by Timple** [pal-robotics/backward_ros#9]
Pretty much a request in line with most other closed issues in this repo :smile: 

Thanks for such a convenient package!

**Comment by bijoua29** [comment]
Also seems this package has not kept up with changes from https://github.com/bombela/backward-cpp/blob/master/backward.hpp. Any plans to do so. Specifically, I had to manually apply https://github.com/bombela/backward-cpp/pull/165 so this package would compile for me with the newer version of binutils.

**Comment by v-lopez** [comment]
I'll try to get in this next week, if you hace anything you can share it would be appreciated.

**Comment by bijoua29** [comment]
Thanks for the great work. Are you going to release a Foxy package so I don't have to build from source.

**Comment by v-lopez** [comment]
Asked release to foxy galactic and rolling.

**Comment by bijoua29** [comment]
So, will this be released as a foxy package? If so, do you know by when?

**Comment by v-lopez** [comment]
By the next foxy sync after they accept my PR.

**Comment by Timple** [comment]
All released :+1:
